### ISSUE TITLE
South and migrations

### ISSUE THREAD

**Issue by versae** [OpenMOOC/moocng#1]
Hi, I am doing some additions in models according to our needs, but there are no migrations at all. Are you guys planning to add South?

**Comment by lorenzogil** [comment]
2012/11/23 Javier de la Rosa notifications@github.com

> Hi, I am doing some additions in models according to our needs, but there
> are no migrations at all. Are you guys planning to add South?

Yes, indeed. We didn't want to add South in the initial development phase.
We plan to add it on the first release, which should happen soon.

**Comment by lorenzogil** [comment]
It's better late than never but we have South now :-)

**Comment by versae** [comment]
Weeee! Thanks a lot, I'll update my code to do proper pull requests from now.
