### ISSUE TITLE
Editing an announcement requires to change title

### ISSUE THREAD

**Issue by versae** [OpenMOOC/moocng#10]
Don't know if fixed with last commits, but so far there is no way to edit an announcement without changing the title. And it's a bit annoying.

**Comment by jespino** [comment]
Works for me.

**Comment by versae** [comment]
Sure. These [two](https://github.com/OpenMOOC/moocng/commit/ff378359598a728f199a1dbd45505a25128cc213#moocng/teacheradmin/views.py) [commits](https://github.com/OpenMOOC/moocng/commit/8d2ea32a814bbec7f35f9d02a6db8511811c8d16#moocng/teacheradmin/views.py) fixed the issue.
