### ISSUE TITLE
Text-decoration shows on .hide-text links hover

### ISSUE THREAD

**Issue by juanxo** [OpenMOOC/moocng#2]
Hi,

Looking at UNED web page, adding hide-text class effectively hides the text but, on hover, the typical text underline appears, leaving an unwanted effect [see pic](http://imgur.com/PbfG1)

PS: Why do you keep a minified version of bootstrap-unedcoma in the repo?

**Comment by pitbulk** [comment]
@ablanco can you handle it?.

The bootstrap-unedcoma.css was added by mistake to the repo when we updated the bootstrap to 2.1.1 (https://github.com/OpenMOOC/moocng/commit/daaf9522c16f88fc2d6c751123a31bab27c6e5d8#moocng/static/css) 

Thanks for report.

**Comment by ablanco** [comment]
I have fixed it in the commit a6738837283ad0dee3f59e3ddce46dcd634766df

Thanks for the report.
