### ISSUE TITLE
Solo tres inconvenientes me separan del exito

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/moocng#24]
Hola compañero que pasa cuando:
1. me pide muchas veces esto en el lado del askbot:

![error](https://f.cloud.github.com/assets/428820/332669/9ce8ec1e-9c35-11e2-8157-6efc1e7571b2.png)

Le digo Continuar muchas veces, cambia los elementos de mas arriba y no pasa nada.
1. Cuando quiero adjuntar un pdf a una pildora de curso me presenta esto:

![erroradjuntos](https://f.cloud.github.com/assets/428820/332668/9753d1ce-9c35-11e2-9b92-32dbc8981ff3.png)
1. En las preguntas, coloco el link de youtube y le digo:

![errorpregunta](https://f.cloud.github.com/assets/428820/332667/91d04a5c-9c35-11e2-950b-25755b5ec5e3.png)

y al parecer se me queda patinando:

![errorpregunta2](https://f.cloud.github.com/assets/428820/332666/8de28f86-9c35-11e2-94ba-51a2cc6d42b2.png)

Solo con f5 me lleva directamente a la zona de 

![fondopregunta](https://f.cloud.github.com/assets/428820/332665/89ebdbe4-9c35-11e2-84c0-6fe974e99358.png)

Yo tengo supuestamente descargado y configurado en los settings el ffmpeg en el path correcto, por que no me funciona el procesamiento de video?

![fondopreguntados](https://f.cloud.github.com/assets/428820/332662/84a52d7a-9c35-11e2-88d6-fa92f747b811.png)

O no tiene nada que ver el ffmpeg?

**Comment by satyaakam** [comment]
again here too i would not be able to help much because of the Language , but there is a way out , we can install using English then change the locale later , what do you say ?

**Comment by johnfelipe** [comment]
Hello again:

In modules i want attach a pdf file and give me this error:

"something went wrong, please try again later."

**Comment by satyaakam** [comment]
@johnfelipe check for permissions on the directory , who owns it and what is the user you are trying to upload as 

-Satya

**Comment by johnfelipe** [comment]
i use:

$ chown apache:apache /var/www/moocng/media
$ chown apache:apache /var/www/moocng/static
$ service httpd restar

And error persist

**Comment by johnfelipe** [comment]
Other error is when "save change and add questions", 

only get this:

![errorpregunta2](https://f.cloud.github.com/assets/428820/332666/8de28f86-9c35-11e2-94ba-51a2cc6d42b2.png)

with f5 keyboard send me directly to this zone: 

![fondopregunta](https://f.cloud.github.com/assets/428820/332665/89ebdbe4-9c35-11e2-84c0-6fe974e99358.png)
