### ISSUE TITLE
key error with admin account

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/moocng#27]
Hi, when log out my admin user, i get this error:

"KeyError at /saml2/logout/
'_saml2_subject_id'
Request Method: GET
Request URL:    http://moocng.felipeurrego.com/saml2/logout/
Django Version: 1.4.1
Exception Type: KeyError
Exception Value:  
'_saml2_subject_id'
Exception Location: /var/www/moocng/lib/python2.6/site-packages/django/contrib/sessions/backends/base.py in __getitem__, line 39
Python Executable:  /usr/bin/python
Python Version: 2.6.6
Python Path:  
['/var/www/moocng/saml2/attribute-maps',
 '/var/www/moocng/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/pip-1.3.1-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/python_memcached-1.48-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/django_compressor-1.1.2-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/PIL-1.1.7-py2.6-linux-x86_64.egg',
 '/var/www/moocng/lib/python2.6/site-packages/djangosaml2-0.7.0-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/pymongo-2.4.2-py2.6-linux-x86_64.egg',
 '/var/www/moocng/lib/python2.6/site-packages/psycopg2-2.4.2-py2.6-linux-x86_64.egg',
 '/var/www/moocng/lib/python2.6/site-packages/South-0.7.6-py2.6.egg',
 '/var/www/moocng/django-tastypie',
 '/var/www/moocng/lib/python2.6/site-packages/python_dateutil-1.5-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/mimeparse-0.1.3-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/django_tinymce-1.5.1b2-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/django_celery-3.0.11-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/django_admin_sortable-1.3.8-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/celery-3.0.11-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/boto-2.8.0-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/django_appconf-0.6-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/pysaml2-0.4.1-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/pytz-2013b-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/kombu-2.5.8-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/billiard-2.7.3.23-py2.6-linux-x86_64.egg',
 '/var/www/moocng/lib/python2.6/site-packages/six-1.3.0-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/importlib-1.0.2-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/repoze.who-1.0.18-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/zope.interface-4.0.5-py2.6-linux-x86_64.egg',
 '/var/www/moocng/lib/python2.6/site-packages/Paste-1.7.5.1-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/httplib2-0.8-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/decorator-3.4.0-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/ordereddict-1.1-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/amqp-1.0.10-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/anyjson-0.3.3-py2.6.egg',
 '/var/www/moocng/moocng',
 '/var/www/moocng/lib/python2.6/site-packages/BeautifulSoup-3.2.0-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages',
 '/var/www/moocng/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/python_memcached-1.48-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/pymongo-2.4.2-py2.6-linux-x86_64.egg',
 '/var/www/moocng/lib/python2.6/site-packages/mimeparse-0.1.3-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/django_appconf-0.6-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/pytz-2013b-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/six-1.3.0-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/importlib-1.0.2-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/ordereddict-1.1-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/BeautifulSoup-3.2.0-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/python_memcached-1.48-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/pymongo-2.4.2-py2.6-linux-x86_64.egg',
 '/var/www/moocng/lib/python2.6/site-packages/mimeparse-0.1.3-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/django_appconf-0.6-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/pytz-2013b-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/six-1.3.0-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/importlib-1.0.2-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/ordereddict-1.1-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/BeautifulSoup-3.2.0-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/python_memcached-1.48-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/pymongo-2.4.2-py2.6-linux-x86_64.egg',
 '/var/www/moocng/lib/python2.6/site-packages/mimeparse-0.1.3-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/django_appconf-0.6-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/pytz-2013b-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/six-1.3.0-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/importlib-1.0.2-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/ordereddict-1.1-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/python_memcached-1.48-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/pymongo-2.4.2-py2.6-linux-x86_64.egg',
 '/var/www/moocng/lib/python2.6/site-packages/mimeparse-0.1.3-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/django_appconf-0.6-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/pytz-2013b-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/six-1.3.0-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/importlib-1.0.2-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/ordereddict-1.1-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/BeautifulSoup-3.2.0-py2.6.egg',
 '/var/www/moocng/lib/python2.6/site-packages/BeautifulSoup-3.2.0-py2.6.egg',
 '/usr/lib/python2.6/site-packages/virtualenv-1.9.1-py2.6.egg',
 '/usr/lib64/python26.zip',
 '/usr/lib64/python2.6',
 '/usr/lib64/python2.6/plat-linux2',
 '/usr/lib64/python2.6/lib-tk',
 '/usr/lib64/python2.6/lib-old',
 '/usr/lib64/python2.6/lib-dynload',
 '/usr/lib64/python2.6/site-packages',
 '/usr/lib64/python2.6/site-packages/PIL',
 '/usr/lib/python2.6/site-packages',
 '/usr/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg-info']
Server time:    vie, 5 Abr 2013 15:04:46 +0200"

**Comment by pitbulk** [comment]
If you log in the platform using the django admin interface you can't later try to log out using the SAML workflow.
