### ISSUE TITLE
No scoring units

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/moocng#33]
Hi, please tell me how scoring units for continue in demo enviroment localhost:8000

Tnks

**Comment by pitbulk** [comment]
Read documentation.

https://github.com/OpenMOOC/moocng/blob/master/docs/source/teacher_manual.rst

**Comment by johnfelipe** [comment]
How activate old scoring method?

Tnks

**Comment by pitbulk** [comment]
Set a list with the slugs of the courses that you want to configure with the "old style mark calculation" in the settings.py to the COURSES_USING_OLD_TRANSCRIPT var.

Ex.

COURSES_USING_OLD_TRANSCRIPT = ['slug_course1', 'slug_course2']

**Comment by johnfelipe** [comment]
UNED deploy:

![plataformamooc-0045](https://f.cloud.github.com/assets/428820/370619/1941a24a-a2fa-11e2-91e7-7f726d529a87.png)

Myself deploy:

![plataformamooc-0044](https://f.cloud.github.com/assets/428820/370615/fd68c684-a2f9-11e2-9376-8f624915ee54.png)

**Comment by johnfelipe** [comment]
sorry, but how scoring this units, my modules is:

![plataformamooc-0046](https://f.cloud.github.com/assets/428820/370636/fb1a6bfc-a2fa-11e2-8513-7c1f71de4233.png)

and nuggets example is:

![plataformamooc-0047](https://f.cloud.github.com/assets/428820/370639/0f265746-a2fb-11e2-80a5-7351f9045bd2.png)

both weight are fine?

**Comment by pitbulk** [comment]
I already said to you.

In normal mark calculation transcript the normal units does not count to mark calculation.
You may enable the "old style mark calculation" in the settings.py

Set COURSES_USING_OLD_TRANSCRIPT var with a list of the slug courses that you want to enable.

**Comment by johnfelipe** [comment]
It works, tnks
