### ISSUE TITLE
Error with certificate of completion

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/moocng#34]
Hi, please tell me about this error:

Click to:

![plataformamooc-0048](https://f.cloud.github.com/assets/428820/370700/37755f5a-a2fe-11e2-90cb-ab9ce309c700.png)

and error is:

![plataformamooc-0049](https://f.cloud.github.com/assets/428820/370736/08a72058-a300-11e2-9945-cf3f44ccfef7.png)

**Comment by pitbulk** [comment]
This functionality require that you use an external certification platform.
OpenMOOC only give you the oportunity to connect with the certification platform,

**Comment by johnfelipe** [comment]
What certification platform you have recommended me

**Comment by pitbulk** [comment]
The UNED university has its own. No idea about what certification platform you have to use.
