### ISSUE TITLE
Khan exercise

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/moocng#58]
Hi please tell me if possible merge khan exercise?

TNKS

**Comment by ablanco** [comment]
It's not possible.

**Comment by johnfelipe** [comment]
Or with https://github.com/learningequality/ka-lite

How i can add mor functionality for nuggets....

**Comment by ablanco** [comment]
You'll have to write code. Create a new [media content](https://github.com/OpenMOOC/moocng/tree/master/moocng/media_contents).
