### ISSUE TITLE
view in android tablet internet browser

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/moocng#60]
Hi, please tell me if chrome or firefox tablet not supported for select Change password in list

**Comment by ablanco** [comment]
It should work fine in Android tablets with Chrome or FFox.

**Comment by johnfelipe** [comment]
I cant select profile settings in menu, in chrome and firefox, help....

**Comment by ablanco** [comment]
It was recently fixed, you need to use the latest code available in the repository.

**Comment by johnfelipe** [comment]
I can update in apache version, no nginx version?

**Comment by ablanco** [comment]
You can use whatever server you want if you deploy it yourself. There aren't two versions of the code.

If you are using the rpm packages, they expect nginx, not apache.

**Comment by johnfelipe** [comment]
Im use old version, but how update my need?

**Comment by johnfelipe** [comment]
This is my code for update mooc engine:

```
    cd /var/www/moocng
    git clone git://github.com/OpenMOOC/moocng.git
    source /var/www/moocng/bin/activate
    cd /var/www/moocng/moocng
```

and django-admin.py collectstatic --settings=moocng.settings

is ok or not
