### ISSUE TITLE
previous nugget unlock

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/moocng#64]
Hi openmooc have ability to activate nugget reading the previous?

TNks

**Comment by ablanco** [comment]
I'm sorry, but that just indecipherable to me. I can't make heads or tails of that sentence...

**Comment by johnfelipe** [comment]
Es decir se puede condicionar la píldora B, si no se ha visto la Píldora A?

**Comment by ablanco** [comment]
No, it's not possible. The content of a nugget can't depend on the previous one.

**Comment by johnfelipe** [comment]
why?, something like udemy or coursera conditional?

**Comment by ablanco** [comment]
Because is not implemented, OpenMOOC doesn't support it.

**Comment by johnfelipe** [comment]
Ok, but possible implementation for future?
Tnks

**Comment by ablanco** [comment]
It is not currently planned. I wouldn't expect it anytime soon.
