### ISSUE TITLE
Contact form doesn't send sender email

### ISSUE THREAD

**Issue by versae** [OpenMOOC/moocng#7]
The mail sent by the contact form, formerly `/complatins/`, does not send any information about the sender email, making difficult to reply students.

I did [some changes](https://github.com/CulturePlex/moocng/blob/master/moocng/complaints/views.py#L23) that you may use if applicable.

**Comment by pitbulk** [comment]
Partially merged on 22024e7a8c3c0c5a75fc0dacb92306792e0f9e5b and cf67b515b1c752f43911654b23f2b5b9f861e642

In our platform the username equals the email, that's why we have merged this partially.
